"use strict";
module.exports = {
  config: {
    updateChannel: "stable",
    fontSize: 18.5,
    fontFamily: '"Monofur Nerd Font Propo", monospace',
    fontWeight: "normal",
    fontWeightBold: "bold",
    cursorColor: "#00ffe5",
    cursorAccentColor: "#000",
    cursorShape: "UNDERLINE",
    cursorBlink: true,
    foregroundColor: "#00ff55",
    backgroundColor: "rgba(0,0,0,0.6)",
    selectionColor: "#7d8cb3",
    borderColor: "rgba(0,0,0,0.0)",
    // css: `.splitpane_divider { background-color: cyan !important; }`,
    padding: "0px 0px 0px 0px",
    colors: {
      black: "#000000",
      red: "#ff3d5a",
      green: "#00f7ff",
      yellow: "#C7C329",
      blue: "#0095E0",
      magenta: "#fff426",
      cyan: "#26fff4",
      white: "#ffffff",
      lightBlack: "#777777",
      lightRed: "#ff0000",
      lightGreen: "#67F86F",
      lightYellow: "#FFFA72",
      lightBlue: "#00d0ff",
      lightMagenta: "#FD7CFC",
      lightCyan: "#68FDFE",
      lightWhite: "#FFFFFF",
      limeGreen: "#32CD32",
      lightCoral: "#ff94bf",
    },
    // shell: "/bin/zsh",
    // shell: "/usr/local/bin/fish",
    // shellArgs: [
    //   "-l",
    //   "-c",
    //   "tmux attach -t ngocute || tmux new-session -s ngocute -n ngocdangyeu",
    // ],
    env: {},
    copyOnSelect: true,
    defaultSSHApp: true,
    quickEdit: false,
    modifierKeys: { altIsMeta: true },
    showHamburgerMenu: "false",
    showWindowControls: "false",
    // hyperBorder: {
    //   animate: true,
    //   borderColors: ["#fc1da7", "#fba506"],
    //   borderWidth: "10px",
    // },
    // opacity: 0.8,
  },
  plugins: [
    // "hyperpower",
    // "hyper-letters",
    // "hyperborder",
    "hyperminimal",
    // "dracula",
    // "hyper-bloodbath",
    // "hyper-opacity",
    // "hyper-transparent",
    // "hyper-background",
    "hyper-save-windowstate",
    // "hyperlinks"
  ],
  localPlugins: [],
  keymaps: {
    "pane:splitRight": "ctrl+x",
    "pane:splitDown": "ctrl+q",
    "pane:close": "ctrl+w",
    "editor:moveBeginningLine": "ctrl+left",
    "editor:moveEndLine": "ctrl+right",
  },
};
