"use strict";
module.exports = {
  config: {
    updateChannel: "stable",
    fontSize: 18.5,
    fontFamily: '"Monofur Nerd Font Propo", monospace',
    fontWeight: "normal",
    fontWeightBold: "bold",
    cursorColor: "#f2cd96",
    cursorAccentColor: "#000",
    cursorShape: "UNDERLINE",
    cursorBlink: true,
    foregroundColor: "#a2cee0",
    backgroundColor: "rgba(0,0,0,0.8)",
    selectionColor: "#7d8cb3",
    borderColor: "rgba(0,0,0,0.0)",
    // css: `.splitpane_divider { background-color: cyan !important; }`,
    padding: "0px 0px 0px 0px",
    colors: {
      black: "#000000",
      red: "#ff3d5a",
      green: "#89f587",
      yellow: "#c2919f",
      blue: "#bb91c4",
      magenta: "#757575",
      cyan: "#9be092",
      white: "#ffffff",
      lightBlack: "#777777",
      lightRed: "#e06060",
      lightGreen: "#abe4ff",
      lightYellow: "#b09679",
      lightBlue: "#707070",
      lightMagenta: "#f7f3a8",
      lightCyan: "#a3e5ff",
      lightWhite: "#FFFFFF",
      limeGreen: "#801155",
      lightCoral: "#ff94bf",
    },
    // shell: "/bin/zsh",
    // shell: "/usr/local/bin/fish",
    // shellArgs: [
    //   "-l",
    //   "-c",
    //   "tmux attach -t ngocute || tmux new-session -s ngocute -n ngocdangyeu",
    // ],
    env: {},
    copyOnSelect: true,
    defaultSSHApp: true,
    quickEdit: false,
    modifierKeys: { altIsMeta: true },
    showHamburgerMenu: "false",
    showWindowControls: "false",
    // hyperBorder: {
    //   animate: true,
    //   borderColors: ["#fc1da7", "#fba506"],
    //   borderWidth: "10px",
    // },
    // opacity: 0.8,
  },
  plugins: [
    // "hyperpower",
    // "hyper-letters",
    // "hyperborder",
    "hyperminimal",
    // "dracula",
    // "hyper-bloodbath",
    // "hyper-opacity",
    // "hyper-transparent",
    // "hyper-background",
    "hyper-save-windowstate",
    // "hyperlinks"
  ],
  localPlugins: [],
  keymaps: {
    "pane:splitRight": "ctrl+x",
    "pane:splitDown": "ctrl+q",
    "pane:close": "ctrl+w",
    "editor:moveBeginningLine": "ctrl+left",
    "editor:moveEndLine": "ctrl+right",
  },
};
