return {
	-- { "echasnovski/mini.splitjoin", version = "*" },
	-- { "echasnovski/mini.indentscope", version = "*" },

	-- {
	-- 	"j-hui/fidget.nvim",
	-- 	event = "LspAttach",
	-- 	tag = "legacy",
	-- 	config = function()
	-- 		require("fidget").setup({
	-- 			text = {
	-- 				spinner = "meter",
	-- 			},
	-- 			window = {
	-- 				blend = 0, -- set 0 if using transparent background, otherwise set 100
	-- 			},
	-- 		})
	-- 	end,
	-- },
	-- { "neoclide/coc.nvim", build = "npm ci" },
	-- { "akinsho/bufferline.nvim", version = "*" },
	-- { "airblade/vim-gitgutter", opts = {} },
	-- "stevearc/oil.nvim"
	-- "gelguy/wilder.nvim",
	-- "ggandor/leap.nvim"
	-- "RRethy/vim-illuminate",
	-- "folke/todo-comments.nvim",
	-- "folke/trouble.nvim",
	-- "feline-nvim/feline.nvim",
	-- "stevearc/conform.nvim",
	-- "simrat39/symbols-outline.nvim"
	-- "stevearc/aerial.nvim"
	-- "terrortylor/nvim-comment",
	-- "rktjmp/lush.nvim",
	-- "ibhagwan/fzf-lua",
	-- {
	-- 	"nvimdev/dashboard-nvim",
	-- 	event = "VimEnter",
	-- 	dependencies = { "nvim-tree/nvim-web-devicons" },
	-- },
	-- {
	-- 	"numToStr/Comment.nvim",
	-- 	lazy = false,
	-- 	dependencies = { "JoosepAlviste/nvim-ts-context-commentstring" },
	-- },
}
