#!/usr/bin/env sh

yabai -m config mouse_follows_focus on
# yabai -m config focus_follows_mouse autoraise
yabai -m config window_shadow float
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.15
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.75
yabai -m rule --add app="Code" opacity=0.85
yabai -m rule --add app="Finder" opacity=0.9
