#!/bin/zsh

alias c='clear'
alias f='fuck'
alias omp='oh-my-posh'

# ssh forward
alias stn='function _stn(){ sport=$2; lport=$(if [ ! -z "$3" ]; then echo $3; else echo $2; fi); ssh -tL ${lport}:localhost:${sport} $1; }; _stn $@'

# alias copy='function _copy(){ pbcopy < $1; }; _copy $@'
alias copy='clipcopy'

# alias for exa
alias ls='exa --icons --color=always --group --time-style=long-iso'
alias l='ls -laH'
alias la='ls -a'
alias ll='ls -l'
alias lla='ls -la'

alias glo='forgit::log'
alias gd='forgit::diff'
alias ga='forgit::add'

# docker-compose
alias dc='docker-compose'
alias dcu='docker-compose up -d'
alias dcd='docker-compose down'

# trash files or folders instead of pernamently remove them
alias rm='trash-put'

# vim and nvim command
alias v='vim'
alias nv='nvim'
alias n='nvim'
alias 'n.'='nvim .'

# lolcat wrapping
lolcat_cmds=(brew cat conda docker docker-compose du fd head more man pip rg tail)
local args='$@'
for cmd in "${lolcat_cmds[@]}"; do
  if command -v $cmd &>/dev/null; then
    eval "${cmd}() { command ${cmd} $args | lolcat }"
  fi
done
